<?php

$pacom_company = array(
	array(
		"ABN" => "",
		"Address 2" => "",
		"Suburb" => "Uniontown",
		"State" => "Ohio",
		"Post Code" => "44685",
		"Country" => "us-pa",
		"Postal Address 1" => "3800 Tabs Drive",
		"Postal Address 2" => "",
		"Postal Suburb" => "Uniontown",
		"Postal State" => "Ohio",
		"Postal Post Code" => "44685",
		"Postal Coutry" => "us-pa",
		"Toll Free" => "1-800-548-4478",
		"Phone" => "1-330-498-2008",
		"Mobile" => "",
		"Email" => "michael.emerick@securitases.com",
		"Web" => "",
		"Image" => "090203040152-gqaq2k2d-Diebold_blue_1inch.jpg",
		"Unison Access" => "n",
		"Contact" => "John Krom",
		"Username" => "diebold",
		"Comments" => "2009-02-03 04:01:52 - details updated by user: Doug Andrea&amp;lt;br /&amp;gt;2009-03-19 18:25:40 - details updated by user: Damien Wilson&amp;lt;br /&amp;gt;2009-06-25 23:52:28 - details updated by user: Bob Morrow&amp;lt;br /&amp;gt;2009-06-25 23:52:29 - details updated by user: Bob Morrow&amp;lt;br /&amp;gt;2009-06-25 23:52:43 - details updated by user: Bob Morrow&amp;lt;br /&amp;gt;2010-01-09 04:59:52 - details updated by user: Steve Tateishi&amp;lt;br /&amp;gt;2010-05-13 21:43:51 - details updated by user: David Garlick&amp;lt;br /&amp;gt;2010-05-21 17:14:53 - details updated by user: John Harvey&amp;lt;br /&amp;gt;2010-08-16 15:02:22 - details updated by user: David Garlick&amp;lt;br /&amp;gt;2013-11-22 06:54:25 - details updated by user: Steve Tateishi&amp;lt;br /&amp;gt;2013-11-27 03:11:48 - details updated by user: Aaron Bradshaw&amp;lt;br /&amp;gt;2013-11-27 20:40:04 - details updated by user: Steve Tateishi&amp;lt;br /&amp;gt;2014-01-18 13:47:47 - details updated by user: Aaron Bradshaw&amp;lt;br /&amp;gt;2014-02-12 16:38:35 - details updated by user: David Gipson&amp;lt;br /&amp;gt;2015-06-30 13:37:25 - details updated by user: David Gipson&amp;lt;br /&amp;gt;2016-02-19 07:55:54 - details updated by user: Junior Ordonez&amp;lt;br /&amp;gt;2016-04-19 16:15:39 - details updated by user: Mikey Emerick&lt;br /&gt;2017-07-28 13:36:12 - details updated by user: Charles Fowlkes\n",
		"Papcom Office" => "2",
		"Creation Date" => "2002-02-11 10:06:47",
		"Last Updated" => "2017-07-28 13:36:12",
	),
	array(
		"ABN" => "",
		"Address 2" => "",
		"Suburb" => "",
		"State" => "",
		"Post Code" => "",
		"Country" => "",
		"Postal Address 1" => "",
		"Postal Address 2" => "",
		"Postal Suburb" => "",
		"Postal State" => "",
		"Postal Post Code" => "",
		"Postal Coutry" => "",
		"Toll Free" => "",
		"Phone" => "",
		"Mobile" => "",
		"Email" => "",
		"Web" => "",
		"Image" => "",
		"Unison Access" => "n",
		"Contact" => "",
		"Username" => "dieboldlas",
		"Comments" => "",
		"Papcom Office" => "2",
		"Creation Date" => "0000-00-00 00:00:00",
		"Last Updated" => "0000-00-00 00:00:00",
	),
	array(
		"ABN" => "",
		"Address 2" => "Finch Drive",
		"Suburb" => "Leeds",
		"State" => "West Yorkshire",
		"Post Code" => "LS15 9JQ",
		"Country" => "gb",
		"Postal Address 1" => "First Floor Unit 7",
		"Postal Address 2" => "Finch Drive",
		"Postal Suburb" => "Leeds",
		"Postal State" => "West Yorkshire",
		"Postal Post Code" => "LS15 9JQ",
		"Postal Coutry" => "gb",
		"Toll Free" => "",
		"Phone" => "00441138921144",
		"Mobile" => "",
		"Email" => "simon.jones@pacom.com",
		"Web" => "",
		"Image" => "",
		"Unison Access" => "n",
		"Contact" => "jesusp",
		"Username" => "dieboldmx",
		"Comments" => "2009-01-15 10:51:24 - details updated by user: Fernando Campa&amp;lt;br /&amp;gt;2013-06-22 18:03:54 - details updated by user: Sinuhe Salvador&amp;lt;br /&amp;gt;2013-09-03 19:12:12 - details updated by user: Sinuhe Salvador Ortega&amp;lt;br /&amp;gt;2013-11-29 17:39:49 - details updated by user: Sinuhe Salvador Ortega&amp;lt;br /&amp;gt;2014-02-12 21:53:51 - details updated by user: Sinuhe Salvador Ortega&amp;lt;br /&amp;gt;2014-12-29 19:02:58 - details updated by user: Fernando Campa&amp;lt;br /&amp;gt;2014-12-29 19:03:44 - details updated by user: Fernando Campa&amp;lt;br /&amp;gt;2014-12-29 19:08:03 - details updated by user: Fernando Campa&amp;lt;br /&amp;gt;2016-01-25 14:00:32 - details updated by user: Harry Gurappa&amp;lt;br /&amp;gt;2016-02-03 04:33:48 - details updated by user: Harry Gurappa&amp;lt;br /&amp;gt;2016-02-04 11:18:32 - details updated by user: Harry Gurappa&amp;lt;br /&amp;gt;2016-02-04 15:03:47 - details updated by user: Harry Gurappa&amp;lt;br /&amp;gt;2016-02-04 15:44:00 - details updated by user: Harry Gurappa&amp;lt;br /&amp;gt;2016-02-04 15:44:26 - details updated by user: Harry Gurappa&amp;lt;br /&amp;gt;2016-02-04 15:55:10 - details updated by user: Harry Gurappa&amp;lt;br /&amp;gt;2016-02-04 15:58:47 - details updated by user: Harry Gurappa&amp;lt;br /&amp;gt;2019-12-20 14:27:27 - details updated by user: Simon Jones&lt;br /&gt;2020-01-03 11:18:35 - details updated by user: Simon Jones\n",
		"Papcom Office" => "2",
		"Creation Date" => "2002-10-16 13:12:05",
		"Last Updated" => "2020-01-03 11:18:35",
	),
	array(
		"ABN" => "",
		"Address 2" => "Torre D, Of.D-11. Chuao",
		"Suburb" => "Caracas",
		"State" => "Distrito Capital",
		"Post Code" => "1060",
		"Country" => "ve",
		"Postal Address 1" => "Av. La Estancia, Centro Banaven,",
		"Postal Address 2" => "Torre D, Of.D-11. Chuao",
		"Postal Suburb" => "Caracas",
		"Postal State" => "Distrito Capital",
		"Postal Post Code" => "1060",
		"Postal Coutry" => "ve",
		"Toll Free" => "",
		"Phone" => "+58 212 9595012",
		"Mobile" => "+58 412 2260008",
		"Email" => "enrique.lugo@diebold-oltp.com.ve",
		"Web" => "http://www.diebold.com",
		"Image" => "081217092936-hjfjbrk7-LogoDOLTP.JPG",
		"Unison Access" => "n",
		"Contact" => "",
		"Username" => "Diebold-Vzla",
		"Comments" => "2008-12-17 09:29:36 - details updated by user: Enrique Lugo&lt;br /&gt;2013-01-08 19:32:51 - details updated by user: Enrique Lugo\n",
		"Papcom Office" => "2",
		"Creation Date" => "0000-00-00 00:00:00",
		"Last Updated" => "2013-01-08 19:32:51",
	),
	array(
		"ABN" => "",
		"Address 2" => "Cau Giay District",
		"Suburb" => "Hanoi",
		"State" => "",
		"Post Code" => "0",
		"Country" => "vn",
		"Postal Address 1" => "No. 27, Group 43, Quan Hoa Ward",
		"Postal Address 2" => "Cau Giay District",
		"Postal Suburb" => "Hanoi",
		"Postal State" => "",
		"Postal Post Code" => "0",
		"Postal Coutry" => "vn",
		"Toll Free" => "",
		"Phone" => "+84 4 37153356",
		"Mobile" => "",
		"Email" => "trieuth@tnt-tech.vn",
		"Web" => "",
		"Image" => "",
		"Unison Access" => "n",
		"Contact" => "",
		"Username" => "tnt-technologies",
		"Comments" => "2015-10-27 04:00:43 - created by Andrew Minnikin via admin system\n",
		"Papcom Office" => "1",
		"Creation Date" => "2015-10-27 04:00:43",
		"Last Updated" => "2015-10-27 04:00:43",
	),
	array(
		"ABN" => "",
		"Address 2" => "",
		"Suburb" => "",
		"State" => "",
		"Post Code" => "",
		"Country" => "",
		"Postal Address 1" => "",
		"Postal Address 2" => "",
		"Postal Suburb" => "",
		"Postal State" => "",
		"Postal Post Code" => "",
		"Postal Coutry" => "",
		"Toll Free" => "",
		"Phone" => "",
		"Mobile" => "",
		"Email" => "",
		"Web" => "",
		"Image" => "",
		"Unison Access" => "n",
		"Contact" => "",
		"Username" => "DigiSurv",
		"Comments" => "",
		"Papcom Office" => "2",
		"Creation Date" => "0000-00-00 00:00:00",
		"Last Updated" => "0000-00-00 00:00:00",
	),
	array(
		"ABN" => "",
		"Address 2" => "SURCO",
		"Suburb" => "Lima",
		"State" => "LIMA",
		"Post Code" => "LIMA 33",
		"Country" => "pe",
		"Postal Address 1" => "AV. LOS PROCERES 250",
		"Postal Address 2" => "SURCO",
		"Postal Suburb" => "Lima",
		"Postal State" => "LIMA",
		"Postal Post Code" => "LIMA 33",
		"Postal Coutry" => "pe",
		"Toll Free" => "",
		"Phone" => "+51 1 4112911",
		"Mobile" => "",
		"Email" => "mvelascoc@gmail.com",
		"Web" => "http://www.prosegur.com.pe",
		"Image" => "121119034513-eabc7v-Prosegur-Logo.jpg",
		"Unison Access" => "n",
		"Contact" => "Martin Velazco",
		"Username" => "disfed",
		"Comments" => "2008-11-19 13:54:54 - details updated by user: Martin Velasco&amp;lt;br /&amp;gt;2010-05-24 21:20:24 - details updated by user: Martin Velasco&amp;lt;br /&amp;gt;2010-05-24 21:26:00 - details updated by user: Martin Velasco&amp;lt;br /&amp;gt;2010-05-24 21:29:03 - details updated by user: Martin Velasco&amp;lt;br /&amp;gt;2010-05-24 21:31:58 - details updated by user: Martin Velasco&amp;lt;br /&amp;gt;2010-05-25 15:32:50 - details updated by user: Martin Velasco&amp;lt;br /&amp;gt;2010-05-25 15:45:18 - details updated by user: Martin Velasco2012-11-19 15:45:13 - details updated by user: Martin Velasco&amp;lt;br /&amp;gt;2013-01-09 13:42:46 - updated by Andrew Minnikin via admin system&amp;lt;br /&amp;gt;2013-09-25 07:58:52 - details updated by user: Martin Velasco&amp;lt;br /&amp;gt;2013-09-25 07:59:38 - details updated by user: Martin Velasco&lt;br /&gt;2016-01-28 01:13:41 - details updated by user: Martin Velasco\n",
		"Papcom Office" => "2",
		"Creation Date" => "2005-01-18 03:31:14",
		"Last Updated" => "2016-01-28 01:13:41",
	),
	array(
		"ABN" => "",
		"Address 2" => "",
		"Suburb" => "",
		"State" => "",
		"Post Code" => "",
		"Country" => "",
		"Postal Address 1" => "",
		"Postal Address 2" => "",
		"Postal Suburb" => "",
		"Postal State" => "",
		"Postal Post Code" => "",
		"Postal Coutry" => "",
		"Toll Free" => "",
		"Phone" => "",
		"Mobile" => "",
		"Email" => "",
		"Web" => "",
		"Image" => "",
		"Unison Access" => "n",
		"Contact" => "",
		"Username" => "drass",
		"Comments" => "",
		"Papcom Office" => "1",
		"Creation Date" => "0000-00-00 00:00:00",
		"Last Updated" => "0000-00-00 00:00:00",
	),
	array(
		"ABN" => "",
		"Address 2" => "",
		"Suburb" => "",
		"State" => "",
		"Post Code" => "",
		"Country" => "",
		"Postal Address 1" => "",
		"Postal Address 2" => "",
		"Postal Suburb" => "",
		"Postal State" => "",
		"Postal Post Code" => "",
		"Postal Coutry" => "",
		"Toll Free" => "",
		"Phone" => "",
		"Mobile" => "",
		"Email" => "",
		"Web" => "",
		"Image" => "",
		"Unison Access" => "n",
		"Contact" => "",
		"Username" => "EasySecurity",
		"Comments" => "",
		"Papcom Office" => "1",
		"Creation Date" => "0000-00-00 00:00:00",
		"Last Updated" => "0000-00-00 00:00:00",
	),
	array(
		"ABN" => "",
		"Address 2" => "",
		"Suburb" => "Atlanta",
		"State" => "GA",
		"Post Code" => "30328",
		"Country" => "us",
		"Postal Address 1" => "1 Concourse Pkwy NE # 300",
		"Postal Address 2" => "",
		"Postal Suburb" => "Atlanta",
		"Postal State" => "GA",
		"Postal Post Code" => "30328",
		"Postal Coutry" => "us",
		"Toll Free" => "",
		"Phone" => "(678) 731-5000",
		"Mobile" => "",
		"Email" => "a@a.com",
		"Web" => "",
		"Image" => "",
		"Unison Access" => "n",
		"Contact" => "",
		"Username" => "Elavon",
		"Comments" => "2011-04-24 09:16:27 - updated by Andrew Minnikin via admin system\n",
		"Papcom Office" => "2",
		"Creation Date" => "0000-00-00 00:00:00",
		"Last Updated" => "2011-04-24 09:16:27",
	),
);

$heads = ['ABN',
'Address 2',
'Suburb',
'State',
'Post Code',
'Country',
'Postal Address 1',
'Postal Address 2',
'Postal Suburb',
'Postal State',
'Postal Post Code',
'Postal Coutry',
'Toll Free',
'Phone',
'Mobile',
'Email',
'Web',
'Contact',
'Username',
'Papcom Office',];

$pacom_company = array(
	array(
		"Note" => "Battery leads wiring incorrectly causing both 1050-001 and 1050-202 faulty",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "PCB badly burnt -Unserviceable",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "Dead - U11 faulty",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "Already replaced - This board will be returned to stock",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "Replaced 2 new batteries",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "Replaced 2 new batteries",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "Possibly wrong polarity on DV supply when connected",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "Please careful when plug connectors in, U3 pins may be shorted together by U5 touching",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "Please careful when plug connectors in, U3 pins may be shorted together by U5 touching",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
	array(
		"Note" => "Please careful when plug connectors in, U3 pins may be shorted together by U5 touching",
		"Component Fault" => NULL,
		"Other Model" => NULL,
		"Fault Found Other" => NULL,
	),
);

$heads = [
    'Note',
    'Component Fault',
    'Other Model',
    'Fault Found Other'
];

$heads = ['Requested Tel',
'Company Name',
'Ret Company',
'Ret Add',
'Ret Tel',
'No Of Received Items',
'No of Requested Items',
'Shipped Date',
'Part-Shipped Date',
'Note',
'Con Note No.1',
'Con Note No.2',
'Courier 1',
'Courier 2',
'Adv Status',
'PartAdv-Shipped Date',
'FullAdv-Shipped Date',
'PartAdv-Note',
'FullAdv-Note',
'PartAdv ConNote',
'FullAdv ConNote',
'PartAdv Courier',
'FullAdv Courier',
'Status Changed By',
'Internal Comment',
'Local Office',
'Currency',
'Confirmed Date',];

$pacom_company = array(
	array(
		"Requested Tel" => "88581750",
		"Company Name" => "pacom",
		"Ret Company" => "pacom",
		"Ret Add" => "6/40 Carrington Rd",
		"Ret Tel" => "88581750",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 2,
		"Shipped Date" => "04 Mar, 2003",
		"Part-Shipped Date" => "28 Feb, 2003",
		"Note" => "TESTTESTTEST",
		"Con Note No.1" => "TESTING",
		"Con Note No.2" => "Test 123",
		"Courier 1" => "NAM TESTING",
		"Courier 2" => "MINNO INC - Testing",
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "1800 832 222",
		"Company Name" => "Bell Technology Services Pty Ltd",
		"Ret Company" => "Bell Technology Services Pty Ltd",
		"Ret Add" => "Unit 6/40 Carrington Rd\r\nCastle Hills NSW 2154\r\n40 Carrington Road\r\nCastle Hill\r\nNSW 2153",
		"Ret Tel" => "1800 832 222",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 3,
		"Shipped Date" => "04 Mar, 2003",
		"Part-Shipped Date" => NULL,
		"Note" => "Received by J Wright   3x 1060",
		"Con Note No.1" => "John Wright",
		"Con Note No.2" => NULL,
		"Courier 1" => "Bell Tech Castle Hill",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "+44 (0)20 8477 7537",
		"Company Name" => "Bell Security",
		"Ret Company" => "Bell Security",
		"Ret Add" => "roding house\r\n970 romford rd\r\nmanor park\r\nlondon \r\ne.12  5.lp",
		"Ret Tel" => "+44 (0)79 9053 1672",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 1,
		"Shipped Date" => "28 Feb, 2003",
		"Part-Shipped Date" => NULL,
		"Note" => "advanced replacement   1x 1067-001-B1  job # 301110",
		"Con Note No.1" => "343 6679 525",
		"Con Note No.2" => NULL,
		"Courier 1" => "DHL",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "03 9396 1686",
		"Company Name" => "Vangren Tech (Vic)",
		"Ret Company" => "Vangren Tech (Vic)",
		"Ret Add" => "11-13 Campbell St\r\nYarraville Vic 3013\r\nAustralia",
		"Ret Tel" => "03 9396 1686",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 3,
		"Shipped Date" => "28 Apr, 2003",
		"Part-Shipped Date" => NULL,
		"Note" => "",
		"Con Note No.1" => "S351522",
		"Con Note No.2" => NULL,
		"Courier 1" => "DIRECT",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "(852)-28505078",
		"Company Name" => "Bell Security (HK) Ltd",
		"Ret Company" => "Bell Security (HK) Ltd",
		"Ret Add" => "20/Floor, AT Tower,\r\n180 Electric Road\r\nHong Kong.",
		"Ret Tel" => "(852)28505078",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 6,
		"Shipped Date" => "07 May, 2003",
		"Part-Shipped Date" => NULL,
		"Note" => "",
		"Con Note No.1" => "3343 6679 923",
		"Con Note No.2" => NULL,
		"Courier 1" => "DHL",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "(852)28505078",
		"Company Name" => "Bell Security (HK) Ltd",
		"Ret Company" => "Bell Security (HK) Ltd",
		"Ret Add" => "20/Floor, AT Tower\r\n180 Electric Road\r\nHong Kong",
		"Ret Tel" => "(852)28505078",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 2,
		"Shipped Date" => "02 Mar, 2004",
		"Part-Shipped Date" => NULL,
		"Note" => "",
		"Con Note No.1" => "3435117851",
		"Con Note No.2" => NULL,
		"Courier 1" => "DHL",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "03 9847 0600",
		"Company Name" => "K.A. Jessup Pty. Limited",
		"Ret Company" => "K.A. Jessup Pty. limited",
		"Ret Add" => "48A Wantirna Rd\r\nRINGWOOD VIC 3134",
		"Ret Tel" => "03 9847 0600",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 3,
		"Shipped Date" => "14 Mar, 2003",
		"Part-Shipped Date" => NULL,
		"Note" => "Advanced Replacement 2 of 2 1058",
		"Con Note No.1" => "S335485",
		"Con Note No.2" => NULL,
		"Courier 1" => "Direct  Couriers",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "03 9466 3266",
		"Company Name" => "Sound Security",
		"Ret Company" => "Sound Security",
		"Ret Add" => "Attn: Jarrod Hall\r\nSound Security\r\n3/33 Commercial Dr\r\nThomastown Vic 3074",
		"Ret Tel" => "03 9466 3266",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 2,
		"Shipped Date" => "14 Apr, 2003",
		"Part-Shipped Date" => NULL,
		"Note" => "",
		"Con Note No.1" => "S351528",
		"Con Note No.2" => NULL,
		"Courier 1" => "DIRECT",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "0208-477-7521",
		"Company Name" => "direct security products",
		"Ret Company" => "direct security products",
		"Ret Add" => "roding house\r\n970 romford rd\r\nmanor park\r\nlondon \r\ne.12  5.lp",
		"Ret Tel" => "0208-477-7521",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 52,
		"Shipped Date" => "09 Oct, 2003",
		"Part-Shipped Date" => NULL,
		"Note" => "",
		"Con Note No.1" => "344 2381 014",
		"Con Note No.2" => NULL,
		"Courier 1" => "DHL",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => "sydney",
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
	array(
		"Requested Tel" => "8620-83556493",
		"Company Name" => "BGB Engineering ltd",
		"Ret Company" => "BGB Engineering Ltd",
		"Ret Add" => "Rm. 103, 1/F.,Hing Yip Commercial Centre,272-284 Des Voeux Road C.,Central,H.K.",
		"Ret Tel" => "8620-83556493 or 00852-25430168",
		"No Of Received Items" => NULL,
		"No of Requested Items" => 10,
		"Shipped Date" => "11 Aug, 2003",
		"Part-Shipped Date" => NULL,
		"Note" => "",
		"Con Note No.1" => "311 2380 594",
		"Con Note No.2" => NULL,
		"Courier 1" => "DHL",
		"Courier 2" => NULL,
		"Adv Status" => NULL,
		"PartAdv-Shipped Date" => NULL,
		"FullAdv-Shipped Date" => NULL,
		"PartAdv-Note" => NULL,
		"FullAdv-Note" => NULL,
		"PartAdv ConNote" => NULL,
		"FullAdv ConNote" => NULL,
		"PartAdv Courier" => NULL,
		"FullAdv Courier" => NULL,
		"Status Changed By" => NULL,
		"Internal Comment" => NULL,
		"Local Office" => NULL,
		"Currency" => NULL,
		"Confirmed Date" => NULL,
	),
);
?>

<table border="1">
    <tr>
        <?php foreach ($heads as $hd): ?>
            <th><?= $hd ?></th>
        <?php endforeach; ?>
    </tr>
    <?php foreach ($pacom_company as $pc): ?>
        <tr>
            <?php foreach ($heads as $hd): ?>
                <td><?= $pc[$hd] ?></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
</table>

<style>
    table td {
    padding: 4px 8px;
}
table {
    font-size: 13px;
    border-collapse: collapse;
    font-family: arial;
}
table th {
    background: #cccccc;
    padding: 4px 8px;
    text-align: center;
}
</style>